object FrmMenu: TFrmMenu
  Left = 0
  Top = 0
  Width = 564
  Height = 339
  TabOrder = 0
  object BtnSaques: TButton
    Left = 12
    Top = 40
    Width = 121
    Height = 45
    Caption = 'Saques'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    OnClick = BtnSaquesClick
  end
  object Button1: TButton
    Left = 12
    Top = 104
    Width = 121
    Height = 45
    Caption = 'Pagamentos'
    Enabled = False
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
  end
  object Button2: TButton
    Left = 12
    Top = 172
    Width = 121
    Height = 45
    Caption = 'Extratos'
    Enabled = False
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
  end
  object Button3: TButton
    Left = 12
    Top = 244
    Width = 121
    Height = 45
    Caption = 'Consultas'
    Enabled = False
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 3
  end
  object Button4: TButton
    Left = 432
    Top = 244
    Width = 121
    Height = 45
    Enabled = False
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 4
  end
  object Button5: TButton
    Left = 432
    Top = 172
    Width = 121
    Height = 45
    Enabled = False
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 5
  end
  object Button6: TButton
    Left = 432
    Top = 104
    Width = 121
    Height = 45
    Enabled = False
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 6
  end
  object BtnManutencao: TButton
    Left = 432
    Top = 40
    Width = 121
    Height = 45
    Caption = 'Manuten'#231#227'o'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -19
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 7
    OnClick = BtnManutencaoClick
  end
end
